ARCHS?=x86_64 arm64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FLAGS+=-mmacosx-version-min=10.9 -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC
LDFLAGS+=-mmacosx-version-min=10.9 -shared $(ARCHOPTS)

# Link against AudioToolbox and CoreFoundation frameworks
LDFLAGS+=-framework AudioToolbox -framework CoreFoundation

LD=clang++
CXX=clang++